import { readFile } from 'node:fs/promises';
import { globSync } from 'node:fs';

const files = [...globSync('*.md'), ...globSync('docs/**/*.md')];
const banned = [/\u2014/u, /Lorem ipsum/iu, /Generated by AI/iu, /Built with AI/iu, /Co-authored-by/iu];
let failed = false;
for (const file of files) {
  const text = await readFile(file, 'utf8');
  for (const pattern of banned) {
    if (pattern.test(text)) {
      process.stderr.write(`${file}: prohibited prose matched ${pattern}\n`);
      failed = true;
    }
  }
}
if (failed) process.exitCode = 1;
